### PR TITLE
use the v4 API; make endpoint configurable; halfassed AccountTeams support

### PR DESCRIPTION
**Pull request by apurvis**
@jarthod

v4 API had a fix I needed for team ownership of surveys (there's still an extant bug; see my ```Survey#teams``` method comment for more details)

The configuration was revamped to be more in line with modern gems.

Other than configuration, my old code that hit the v3 endpoint worked the same.

### CODE REVIEW

**Comment by jarthod** [comment]
Nice work ;)

**Comment by apurvis** [comment]
on our end for our usage, we integrated Pester, our retry gem:
https://github.com/lumoslabs/pester
which we use for AWS and other temporary-problem-prone services.

Given the large # of random timeouts from SG, I was thinking of integrating it into this gem directly.  Are timeouts something you or other users struggle with?

**Comment by jarthod** [comment]
We do experience some timeouts from time to time but I do not think the retry handling should belong to the gem. This is anyway something you don't want by default as it could have dramatic impacts in case of event loops or already retrying systems like job queues.

**Comment by apurvis** [comment]
yeah, good point.

**Pull request merged**
