### PR TITLE
Get rid of error tracking; raise exceptions instead.  

### PR DESCRIPTION
**Pull request by apurvis**
Don't return empty arrays and nil on failures.

@jarthod ripping out more stuff... rather than silently fail and just add stuff to the errors array, now bad responses from SG (including API timeout) should raise exceptions.   It's also much less confusing in the `resource.rb` file's response handling.

error tracking didn't really work anyways...

### CODE REVIEW

**Comment by jarthod** [comment]
Looks nice, thanks ! why `4.0.2` ? should be `3.1.0` or `4.0.0` no ?

**Comment by apurvis** [comment]
it's just my internal tagging, you can feel free to change it before merging back to 4.0.0 if you want.  

4.0.1 was when i dropped the support for `copy`.
4.0.2 is when i refactored the multilingual support to a module

**Comment by apurvis** [comment]
(and i think it would be 4.0 instead of 3.1 because there was a removal of functionality - there's no more `errors` property on the resource objects, and if people were using that their code would break

**Comment by jarthod** [comment]
Ok, I'll release it as 4.0 then

**Comment by jarthod** [comment]
released `4.0.0`

**Pull request merged**
