### PR TITLE
Collapse .all and .first api method signatures to single hash

### PR DESCRIPTION
**Pull request by apurvis**
@jarthod 
This supersedes https://github.com/RipTheJacker/survey-gizmo-ruby/pull/42 but I'm not ready to merge this yet.  Collapsing the method signatures makes everything a lot less user error prone and generally better but is also a majorly breaking change with everyday usage that I have not tested yet.

Other PR should be ready for merge and is only a minor version bump.  Not sure when I will finish this but heads up and feedback appreciated.

### CODE REVIEW

**Comment by jarthod** [comment]
Ok I like the idea, but maybe you could just keep the second parameter and merge it into the first.
This way it won't break anything and we can put this as a minor. Maybe with a deprecation warning if this parameter is present.

Of course the comments, readme and specs should all show the single hash usage as you did.

**Comment by apurvis** [comment]
that's actually a pretty great idea; then we don't need the major version bump.

**Comment by apurvis** [comment]
OK now there's a deprecation warning that will print if you use the 2nd param and the major version doesn't have to increment.

i set version to 4.2 because the other PR is 4.1 and presumably that will be merged first (i've tested that in production)

**Comment by apurvis** [comment]
OK i did some preliminary testing and fixed some bugs; I'll run a full scale test in the next few days at which point i'll give the greenlight on this PR, but so far looks fine.

**Comment by jarthod** [comment]
Great, thanks for your contribution!

**Comment by apurvis** [comment]
for what it's worth, PRs from lumos will only generally be submitted to the project when they have been tested in a fairly massive production environment on the order of hundreds of surveys and millions of responses being retrieved via the API.

**Comment by apurvis** [comment]
but i would kill for some vcr/webmock specs, grr

**Comment by apurvis** [comment]
i had one more minor style commit that didn't end up on this branch, so i'm going to close this and reopen a new PR.

**Pull request closed without merging**
