### PR TITLE
Adds debugging option for raw Httparty output and parsed data output

### PR DESCRIPTION
**Pull request by apurvis**
Debugging code from @chorn's branch
Filters now useable (formerly only filters like the page number would work)
@Intrepidd @adibsaad since you guys seem to have merged to master before.

### CODE REVIEW

**Comment by apurvis** [comment]
If someone notices this PR and wants to merge it I will fix up the version numbers.

**Comment by jarthod** [comment]
Seems good to me, expect for the ruby 2.1.5 version bump. Why is that ?
It seems to be still working on 1.9.3. I've merged this into master, will release after your answer.

**Comment by apurvis** [comment]
I should probably put that file in .gitignore - it's for rbenv which we use to manage ruby versions.  Maybe also if you are going to merge to master I should put the version as just an incremental bump?

Do you want to revert the merge and I'll submit a new PR?  I also put a few more helpful comments on my fork.

**Comment by apurvis** [comment]
Or I mean, if yr cool bumping the version to 2.x then I'll just do the .gitignore... It might confuse bundler down the line (when someone releases a real "2.0" version) at this point to revert the gemspec file and try to change it...

**Comment by jarthod** [comment]
Yep, I know about ruby-version, as you can see I already deleted it and added it to the gitignore in master. I also moved down version to 1.1.0.
My question was more about the {{gem.required_ruby_version = '>= 2.1.5'}} line in the gemspec, this is very restrictive and not usefull at all, I removed it also but I wanted to make sure you didn't do it for a good reason.

**Pull request merged**
