### PR TITLE
Bump major version; add warning to README

### PR DESCRIPTION
**Pull request by apurvis**
@jarthod

### CODE REVIEW

**Comment by jarthod** [comment]
Great, thanks.
I'm just gonna change the "People who need backwards compatibility can use 1.1.7" to 1.0.4 because this is the last version on rubygem.

**Comment by jarthod** [comment]
Released: https://rubygems.org/gems/survey-gizmo-ruby

**Comment by apurvis** [comment]
huh, 39 downloads already?

**Comment by jarthod** [comment]
It seems ^^ some are probably automated

**Pull request merged**
